#!/bin/bash

# removing any previous configuration file about usb storage
usbStorageConfigurationFile="/etc/modprobe.d/usb-storage.conf"
if [ -f "$usbStorageConfigurationFile" ]; then
  rm -f "$usbStorageConfigurationFile"
fi

# creating a new configuration file
echo "install usb-storage /bin/true" > "/etc/modprobe.d/usb-storage.conf"
