#!/bin/bash

# getting current script folder
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# creating neatvideo config folder
configFolder=$HOME/.config/ABSoft

# only doing it in case the configation does not exist
if ! [ -d "$configFolder" ]; then
    mkdir -p $configFolder
    cp $dir/data/neatVideo/NeatVideo4-OFX.conf $configFolder/
fi
