#!/bin/bash

# checking if the computer has a GPU from nvidia
hasNvidiaGPU=`lspci -v | grep NVIDIA`
if ! [[ -z "$hasNvidiaGPU" ]]; then

  # The nvidia driver version follows specification for maya 2018
  # https://knowledge.autodesk.com/sites/default/files/HardwareCertificationResults_Maya2018_v01a.pdf
  driverVersion="384.59-1"

  yum install -y "nvidia-x11-drv-$driverVersion.el7.elrepo.x86_64" --skip-broken
fi
