#!/bin/bash

# creating shotgun desktop folder
mkdir $HOME/.shotgun

# adding the umedia host name to the configuration
echo "{current_host: '$UMEDIA_SHOTGUN_URL'}" > $HOME/.shotgun/authentication.yml
