#!/bin/bash

# getting current script folder
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# creating rv config folder
configFolder=$HOME/.config/TweakSoftware
if ! [ -d "$configFolder" ]; then
    mkdir -p $configFolder
fi

# copying the initial config file config file
cp $dir/data/rv/RV.conf $configFolder/RV.conf
