#!/bin/bash

# Triggered during the initialization as root:
#
# Host type:
# defined as a child of the script type, it tells what is the which kind of host it should
# be executed, this is done by reading the env var $UMEDIA_HOST_TYPE. In case a script
# is meant to be executed in any host then place it under "any" (rather then duplicating it
# accross the hosts...)
#
# Script conventions:
# make sure the scripts have the shebang (#!) and set as executable.

# getting current script folder
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

allFacilities="$dir/allFacilities"
currentFacility="$dir/$UFACILITY_NAME"

for facilityPath in $allFacilities $currentFacility ; do

  superuserAnyScriptPath="$facilityPath/any/$UCORE_OS/$UCORE_OS_VERSION"
  superuserHostTypeScriptPath="$facilityPath/$UMEDIA_HOST_TYPE/$UCORE_OS/$UCORE_OS_VERSION"

  for scriptPath in $superuserAnyScriptPath $superuserHostTypeScriptPath ; do

    # checking if the directory exists
    if ! [ -d "$scriptPath" ]; then
      continue
    fi

    # we want to execute a "main" script first, then everything else after that
    for scriptOrder in "main" "any" ; do
      for executable in $scriptPath/* ; do

        # making sure sure we are executing the main script first
        executableBaseName=$(basename $executable)
        if [[ "$executableBaseName" != "main" && "$scriptOrder" == "main" ]]; then
          continue
        # also, preventing the execution of the main script again when
        # everything else is executed
        elif [[ "$executableBaseName" == "main" && "$scriptOrder" == "any" ]]; then
          continue
        fi

        # making sure it's an executable
        if [[ -f "$executable" &&  -x "$executable" ]]; then
          eval $executable
        fi
      done
    done
  done
done

# at the end of this process the computer gets reboot automatically when
# uevents version is different. The reboot is necessary to make
# sure drivers/kernel/etc are going to take effect properly.
# TODO: ideally we only want to reboot when we have changes under ./root/**,
# however currently the way it's working it looks for the UEVENTS_VERSION
# to decide it (which is not ideal, since isolated changes at login/logout events
# are going to generate a new version of uevents. Therefore,
# forcing to an unecessary reboot).
if ! [ -z "$UEVENTS_VERSION" ]; then
  currentUEventsSystemVersion=""
  ueventsSystemVersionFile="/etc/umediaUEventsVersion"
  if [ -f "$ueventsSystemVersionFile" ]; then
    currentUEventsSystemVersion=$(cat $ueventsSystemVersionFile)
  fi

  # making sure the version has changed
  if ! [[ "$currentUEventsSystemVersion" == "$UEVENTS_VERSION" ]]; then

    # updating /etc/umediaUEventsVersion to tell
    # what is the version that got updated to.
    echo "$UEVENTS_VERSION" > $ueventsSystemVersionFile

    # rebooting system, there is no scape at this point. Good bye, see you soon!
    reboot
  fi
fi
