#!/bin/bash

# Triggered during the initialization as root:
#
# Host type:
# defined as a child of the script type, it tells what is the which kind of host it should
# be executed, this is done by reading the env var $UMEDIA_HOST_TYPE. In case a script
# is meant to be executed in any host then place it under "any" (rather then duplicating it
# accross the hosts...)
#
# Script conventions:
# make sure the scripts have the shebang (#!) and set as executable.

# getting current script folder
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

allFacilities="$dir/allFacilities"
currentFacility="$dir/$UFACILITY_NAME"

for facilityPath in $allFacilities $currentFacility ; do

  superuserAnyScriptPath="$facilityPath/any/$UCORE_OS/$UCORE_OS_VERSION"
  superuserHostTypeScriptPath="$facilityPath/$UMEDIA_HOST_TYPE/$UCORE_OS/$UCORE_OS_VERSION"

  for scriptPath in $superuserAnyScriptPath $superuserHostTypeScriptPath ; do

    # checking if the directory exists
    if ! [ -d "$scriptPath" ]; then
      continue
    fi

    for executable in $scriptPath/* ; do
      # making sure it's an executable
      if [[ -f "$executable" &&  -x "$executable" ]]; then
        eval $executable
      fi
    done
  done
done
