#!/bin/bash

if ! [ -f "/etc/yum.repos.d/nux-dextop.repo" ]; then
  # adding epel repository
  yum install -y epel-release

  # adding nux-desktop repository
  yum install -y http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm
fi

# ipa/freeipa seems broken on centos 7.3:
# https://www.centos.org/forums/viewtopic.php?t=63500
# - Quote: "The ipa/freeipa conflicts are a known bug upstream and will be fixed in 7.4 when that arrives.
# It causes no problems and you can ignore the messages."
yum install -y vlc --skip-broken
yum install -y smplayer ffmpeg

# installing video codecs (https://wiki.centos.org/TipsAndTricks/MultimediaOnCentOS7) used by firefox, nuke...
yum install -y libdvdcss gstreamer{,1}-plugins-ugly gstreamer-plugins-bad-nonfree gstreamer1-plugins-bad-freeworld
